### ISSUE TITLE
[Feature request] Improve fuzzy searching

### ISSUE THREAD

**Issue by andreascmj** [atom/command-palette#114]
Currently the search functionality only shows command that matches the order of the characters in the search string. This means that you need to remember the order of the words of the command to search for it.

Example:
I want to run the command `Theme Switch: Next`
If I start writing `Theme Ne` it will show up, but if I start writing `Next Th` it does not.

To me it would make more sense that the search would be more fuzzy in this case, and not filter out commands based on order of characters.

**Comment by 50Wliu** [comment]
@andreascmj can you confirm that the "Use Alternate Scoring" in Command Palette settings is checked?

**Comment by andreascmj** [comment]
Yes, I see no difference having it checked or unchecked.

To clarify, I would like the `Theme Switch: Next` command to show up in both these cases.

![image](https://user-images.githubusercontent.com/1576086/54522623-ff992400-496d-11e9-9aa1-3cd60a7eeb04.png)

![image](https://user-images.githubusercontent.com/1576086/54522646-09228c00-496e-11e9-8664-f6eb6140c968.png)

**Comment by rsese** [comment]
Thanks for the suggestion @andreascmj :+1:  I chatted with another maintainer and while we think alternative fuzzy search functionality would be useful in general, it's not something the team would prioritize at the moment since we depend on fuzz-aldrin and fuzz-aldrin-plus for results scoring.  So we'll close for now, but we'll definitely keep in mind that different search behavior is something that folks would find useful.
