### ISSUE TITLE
Create Your First Package "activationsCommands" is wrong I think

### ISSUE THREAD

**Issue by jessegrosjean** [atom/command-palette#33]
It says the package.json should look like:

```
"activationCommands": ["ascii-art:convert"],
```

But I think that must have changed, because now in the new project template it needs a selector like:

```
  "activationCommands": {
    "atom-workspace": "ascii-art:convert"
  },
```

I think this change (and old docs) might also be the source of https://github.com/atom/command-palette/issues/30

**Comment by claman** [comment]
This fixed the error for me

**Comment by izuzak** [comment]
This has been fixed in the docs: https://atom.io/docs/latest/hacking-atom-package-modifying-text#trigger-the-command (see https://github.com/atom/docs/pull/19). And I verified that the package generator generates a hash, and not an array, for `activationCommands` in package.json. Let me know if there's still anything to do here.
