### ISSUE TITLE
set syntax not accesible

### ISSUE THREAD

**Issue by muhasturk** [atom/command-palette#45]
Include "Set Syntax" command into palette

**Comment by lee-dohm** [comment]
You have two options:

1. You can use <kbd>Ctrl+Shift+L</kbd> to activate the [language-selector package](https://atom.io/packages/language-selector) which is installed by default
1. You can install my [set-syntax package](https://atom.io/packages/set-syntax) which does add the "Set Syntax" commands into the command palette

**Comment by muhasturk** [comment]
language selector package is not found.

Why do I have to install another package to set syntax? Also this package should be included into Atom.

**Comment by muhasturk** [comment]
Found. You mean [Grammer Selector Package](https://atom.io/packages/grammar-selector).

Control + Shift +  L

**Comment by lee-dohm** [comment]
Yes, sorry about the package name, but the key binding was correct :grinning:

**Comment by muhasturk** [comment]
Why did not you include set syntax package into command palette?

**Comment by lee-dohm** [comment]
Because the Atom team feels the grammar-selector package is sufficient. And I agree with the philosophy that not everything needs to be default-installed.

**Comment by whizkydee** [comment]
Hi @lee-dohm,

I think the `Set Syntax` feature in the command palette should be available by default. Users shouldn't have to install a package to make a core feature like `Set Syntax` available.
I personally love to access features of Atom through the command palette, and I feel other users should love that too, so I think that using the `Ctrl+Shift+L` command feels inconsistent and not so relevant when there is a `Ctrl+Shift+P` command to activate the command palette.
I've been using Atom for years now, and I recently just discovered the `Ctrl+Shift+L` command. I've always been frustrated about having to go to the bottom-right of the screen to select a language.

Also, I don't think the idea that not everything needs to be default-installed is great because having to install new packages slows down Atom, makes the user to install a lot of packages which make the package list lengthy and unmanageable, it also causes the user to update packages irrelevantly as a result of updates to Atom-core or its API; In my frustration, I was about to create a `Set Syntax` package until I discovered this issue.

**PS:** The charset and line-ending selectors should also be available via the command palette. The command palette should be a shortcut to access all the features of Atom just like in VSCode, Sublime Text and others.

Thanks 👍.
