### ISSUE TITLE
Use cmd-P instead of cmd-shift-P

### ISSUE THREAD

**Issue by adius** [atom/command-palette#55]
As already proposed in fuzzy-finder https://github.com/atom/fuzzy-finder/issues/129 I think we should not use the duplicate shortcut `cmd-P` for the fuzzy-finder but instead use it to toggle the command-palette.
As it is "probably the most important command in Atom" (as stated in the flight manual) and should therefore better be assigned to a 2 key instead of a 3 key shortcut.

**Comment by adius** [comment]
No thoughts on this one?

**Comment by thomasjo** [comment]
If we change this, I don't think we can change it until Atom v2.0.0 since this would constitute a "breaking" change. /cc @atom/feedback

**Comment by lee-dohm** [comment]
I agree with @thomasjo, if this is done it should be done for v2.0.

**Comment by terraqout** [comment]
Don't you try bind it by yourself and forget about a "problem"?
I'm using alt-space, it's my choice and I didn't want to dictate it to someone

**Comment by piggyslasher** [comment]
NO way. Why change something that works? I use CMD+P for files, which is what any programmer needs more than the actual command palette. Bind your own shortcuts mate.

**Comment by jdamgo** [comment]
Keybinding is something that is (more or less) unique to every programmer. Everybody has preferences and  reluctances. That's why it's something most editors can fully customize. In atom it's pretty easy as well (short notice: use `unset!` as command to remove a binding). Besides that making sure there are no duplicates can be challanging and if it currently works - customize it locally to your likings.

**Comment by lee-dohm** [comment]
We're not looking at updating keybindings default keybindings except in extreme circumstances at this point.

Thanks for the feedback!
