### ISSUE TITLE
Incredibly Slow Opening.

### ISSUE THREAD

**Issue by jordwalke** [atom/command-palette#74]
The Command Pallet seems to be incredibly slow to open. I'm measuring 200ms on a brand new macbook pro. I would expect something so simple to be rendered in `50ms` maximum.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.
